# Generated by Django 5.0 on 2024-07-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_branch_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='education',
        ),
    ]
