# Generated by Django 5.0 on 2024-07-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jobopening_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='post',
            field=models.URLField(default='None'),
        ),
    ]
