# Generated by Django 5.0 on 2024-07-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_jobopening_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='company',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
