# Generated by Django 5.0 on 2024-07-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_jobopening_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteprofile',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instituteprofile',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='institute_logos/'),
        ),
        migrations.AddField(
            model_name='instituteprofile',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
