# Generated by Django 5.0 on 2024-07-07 13:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=accounts.models.upload_location),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='contact_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='website',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
