# Generated by Django 5.0 on 2024-07-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_recruiterprofile_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cgpa',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
