# Generated by Django 5.0 on 2024-07-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_studentprofile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='institutes_shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_with_recruiters', to='accounts.instituteprofile'),
        ),
    ]
