# Generated by Django 5.0 on 2024-07-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_recruiterprofile_institutes_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='institutes_shared_with',
        ),
    ]
